import { useEffect, useRef } from 'react';
import gsap from 'gsap';
import './Pages.css';

export default function Documentation() {
  const pageRef = useRef(null);

  useEffect(() => {
    if (pageRef.current) {
      gsap.fromTo(pageRef.current.children, 
        { opacity: 0, x: -30 },
        { opacity: 1, x: 0, duration: 0.8, stagger: 0.15, ease: 'power3.out' }
      );
    }
  }, []);

  return (
    <div className="page-container" ref={pageRef}>
      <div className="page-header">
        <h2>API Documentation & Stack</h2>
        <p>Endpoints exposed by the ElysiumSVD Backend and the technologies powering them.</p>
      </div>

      <div className="doc-section glass-panel" style={{ marginBottom: '32px' }}>
        <h3>Technology Stack</h3>
        <ul style={{ paddingLeft: '24px', color: 'var(--text-secondary)', marginTop: '12px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
          <li><strong>Frontend:</strong> React 18, Vite, GSAP (Animations), Recharts (Data Visualization), Lucide React (Icons).</li>
          <li><strong>Backend API:</strong> FastAPI (Python 3), Uvicorn.</li>
          <li><strong>Machine Learning:</strong> Scipy (<code>scipy.sparse.linalg.svds</code>), Numpy (Vector operations), Pandas (Data parsing), Scikit-Learn (Evaluation metrics).</li>
          <li><strong>Persistence:</strong> Joblib (Pickle serialization for instant model loading).</li>
        </ul>
      </div>

      <div className="doc-section glass-panel">
        <div className="endpoint-header">
          <span className="method get">GET</span>
          <span className="path">/recommend/&#123;user_id&#125;</span>
        </div>
        <p className="doc-desc">Returns top N recommended products for a given user. If the user is not found in the latent matrix, a fallback array of globally popular items is returned along with the cold_start flag set to true.</p>
      </div>

      <div className="doc-section glass-panel">
        <div className="endpoint-header">
          <span className="method get">GET</span>
          <span className="path">/similar/&#123;product_id&#125;</span>
        </div>
        <p className="doc-desc">Returns N products most similar to the provided product_id, utilizing cosine similarity across the item latent factor matrix.</p>
      </div>

      <div className="doc-section glass-panel">
        <div className="endpoint-header">
          <span className="method get">GET</span>
          <span className="path">/api/v1/latent-space</span>
        </div>
        <p className="doc-desc">Retrieves 2D coordinates for all products, generated by projecting the high-dimensional latent matrix down to two dimensions (e.g., using PCA or t-SNE during training) for visualization.</p>
      </div>

      <div className="doc-section glass-panel">
        <div className="endpoint-header">
          <span className="method get">GET</span>
          <span className="path">/health</span>
        </div>
        <p className="doc-desc">Standard health check endpoint used to calculate system latency and uptime status.</p>
      </div>
    </div>
  );
}
